version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "7000:7000"
    restart: on-failure
    volumes:
      - ./api-gateway:/src
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
    networks:
      - app_network

networks:
  app_network:


volumes:
  db_data:
  node_modules_front: 