version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "7000:7000"
    restart: on-failure
    volumes:
      - ./api-gateway:/src
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
    networks:
      - app_network

  users-service:
    build: ./users-service
    volumes:
      - ./users-service/src:/usr/app/src
    ports:
      - "7101:7101"
    depends_on:
      - users-service-db

  users-service-db:
    image: mysql:5.7.20
    ports:
      - "7201:3306"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  chat-app:
    build: ./chat-app
    volumes:
      - ./chat-app/src:/usr/app/src
    ports:
      - "7001:7001"
    env_file:
      - ./chat-app/.env
    depends_on:
      - api-gateway

  chat-service:
    build: ./chat-service
    volumes:
      - ./chat-service/src:/usr/app/src
    ports:
      - "7100:7100"
    depends_on:
      - chat-service-db

  chat-service-db:
    image: mysql:5.7.20
    container_name: chat-service-db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports: 
      - 7200:3306


networks:
  app_network:


volumes:
  db_data:
  node_modules_front: 